<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FITS.Lib" Version="4.6.361" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="RtlSdrManager" Version="0.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RASTA.Core\RASTA.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="librtlsdr.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="libusb-1.0.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="libwinpthread-1.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
